"""w5-05 verification — cross-check every headline number of the baseline.

Inputs (sandbox paths):
  /tmp/w502/scan.json          — w5-02 scan artifact (sha256 c4d70013…, verified before run)
  /tmp/w505-triage-table.md    — 244-row triage table regenerated by w505-triage-map.py
  /tmp/w503/compare.json       — w5-03 recall artifact (sha256 2bfd04ea…, verified before run)
  /tmp/w503/audit-results.json — w5-04 verdict block (testdata/audit-results.json @ agent-w5-04)

Fail-closed: any assertion failure exits non-zero and prints which check broke.
"""
import json, sys, collections

fails = []

def check(name, cond, detail=""):
    status = "PASS" if cond else "FAIL"
    print(f"[{status}] {name}" + (f" — {detail}" if detail else ""))
    if not cond:
        fails.append(name)

# ---------- A. scan.json ----------
scan = json.load(open("/tmp/w502/scan.json", encoding="utf-8"))
f = scan["findings"]
check("A1 findings == 244", len(f) == 244, str(len(f)))
sev = collections.Counter(x["severity"] for x in f)
check("A2 severity 24E/143W/77I", (sev["ERROR"], sev["WARN"], sev["INFO"]) == (24, 143, 77),
      f"E={sev['ERROR']} W={sev['WARN']} I={sev['INFO']}")
check("A3 summary.suppressed == 0", scan["summary"]["suppressed"] == 0)
check("A4 files scanned 753 / skipped 9", (scan["summary"]["files"], scan["summary"]["skippedFiles"]) == (753, 9))
check("A5 source java spring-boot 4.0.2",
      (scan["source"]["lang"], scan["source"]["framework"], scan["source"]["frameworkVersion"]) == ("java", "spring-boot", "4.0.2"))
nfiles = len({x["location"]["file"] for x in f})
check("A6 35 files with findings", nfiles == 35, str(nfiles))
per_rule = collections.Counter(x["ruleId"] for x in f)
check("A7 18 rules fired", len(per_rule) == 18, str(len(per_rule)))

# ---------- B. triage table ----------
rows = []
for line in open("/tmp/w505-triage-table.md", encoding="utf-8"):
    line = line.rstrip("\n")
    if line.startswith("| ") and not line.startswith("| #") and not line.startswith("|---"):
        rows.append([c.strip() for c in line.split("|")[1:-1]])
check("B1 table rows == 244", len(rows) == 244, str(len(rows)))
tsev = collections.Counter(r[2] for r in rows)
check("B2 table severity matches scan", all(tsev[s] == sev[s] for s in ("ERROR", "WARN", "INFO")),
      f"E={tsev['ERROR']} W={tsev['WARN']} I={tsev['INFO']}")
verd = collections.Counter(r[5].strip("*") for r in rows)
check("B3 verdicts 129 TP / 115 FP / 0 others",
      (verd["TP"], verd["FP"]) == (129, 115) and set(verd) == {"TP", "FP"},
      f"TP={verd['TP']} FP={verd['FP']}")
# NOTE: expected values below come from the machine-generated per-rule triage table
# (w5-04 §2 per-rule table + scan.json severities), NOT from the hand-written prose
# line in w5-04 §2 ("75 TP / 68 FP WARN, 31 TP / 46 FP INFO") — that prose line does
# not match its own per-rule table; the script recount is authoritative.
vsev = collections.defaultdict(collections.Counter)
for r in rows:
    vsev[r[2]][r[5].strip("*")] += 1
check("B4 ERROR verdicts 23 TP / 1 FP", (vsev["ERROR"]["TP"], vsev["ERROR"]["FP"]) == (23, 1))
check("B5 WARN verdicts 64 TP / 79 FP", (vsev["WARN"]["TP"], vsev["WARN"]["FP"]) == (64, 79))
check("B6 INFO verdicts 42 TP / 35 FP", (vsev["INFO"]["TP"], vsev["INFO"]["FP"]) == (42, 35))
check("B7 TP+FP == 244", verd["TP"] + verd["FP"] == 244)
fp_share = round(100.0 * verd["FP"] / 244, 1)
check("B8 FP share 47.1%", fp_share == 47.1, str(fp_share))

# index consistency: table is grouped by rule; index set must be exactly 0..243
# and each row's rule+severity must match scan.json at that index
idx_ok = {int(r[0]) for r in rows} == set(range(244)) and all(
    r[1] == f[int(r[0])]["ruleId"] and r[2] == f[int(r[0])]["severity"] for r in rows)
check("B9 table index set 0..243 + row identity vs scan", idx_ok)

# ---------- C. compare.json (recall) ----------
cmp_ = json.load(open("/tmp/w505/compare.json", encoding="utf-8"))
check("C1 ref unique 182", cmp_["refTotalUnique"] == 182, str(cmp_["refTotalUnique"]))
check("C2 IR main unique 182", cmp_["irTotalUnique"] == 182, str(cmp_["irTotalUnique"]))
check("C3 matched 182 / FN 0 / extra 0",
      (len(cmp_["matched"]), len(cmp_["fn"]), len(cmp_["extra"])) == (182, 0, 0))
check("C4 recall exact = 1.0", cmp_["recallExact"] == 1.0)
check("C5 ref list 184 / dup 2", (cmp_["refTotalList"], cmp_["refDup"]) == (184, 2))
check("C6 11 src/test endpoints out of scope", len(cmp_["irTestEndpoints"]) == 11)
check("C7 per-class totals sum 184", sum(v["ref"] for v in cmp_["perClass"].values()) == 184,
      str(sum(v["ref"] for v in cmp_["perClass"].values())))

# ---------- D. audit-results.json (w5-04 block) ----------
ar = json.load(open("/tmp/w505/audit-results.json", encoding="utf-8"))
my = ar["military_youth"]
cnt = my["counts"]
check("D1 counts 244/129/115/6/47.1",
      (cnt["findings"], cnt["tp"], cnt["fp"], cnt["fn_candidates"], cnt["fp_share_pct"]) == (244, 129, 115, 6, 47.1))
pr = my["per_rule"]
check("D2 per_rule 18 entries", len(pr) == 18)
check("D3 per_rule findings sum 244", sum(r["findings"] for r in pr) == 244)
pr_ok = all(r["tp"] + r["fp"] == r["findings"] for r in pr)
check("D4 per_rule tp+fp == findings", pr_ok)
pr_match = all(per_rule[r["rule"]] == r["findings"] for r in pr)
check("D5 per_rule findings == scan recount", pr_match)
fnl = my["fn_candidates"]
check("D6 fn_candidates 6 entries", len(fnl) == 6)

# ---------- E. baseline TP-set consistency (regenerated here) ----------
tp_idx = {int(r[0]) for r in rows if r[5].strip("*") == "TP"}
check("E1 TP set size 129", len(tp_idx) == 129)
tp_by_rule = collections.Counter(f[i]["ruleId"] for i in tp_idx)
check("E2 TP by rule top: R3xx-01=20, R4xx-01=8, R1xx-02=14, R2xx-04=14, R3xx-02=24, R4xx-03=11, R2xx-02=12, R5xx-03=12",
      all(tp_by_rule[r] == n for r, n in [("R3xx-01", 20), ("R4xx-01", 8), ("R1xx-02", 14),
                                          ("R2xx-04", 14), ("R3xx-02", 24), ("R4xx-03", 11),
                                          ("R2xx-02", 12), ("R5xx-03", 12)]))

print()
if fails:
    print("RESULT: FAIL —", ", ".join(fails))
    sys.exit(1)
print("RESULT: PASS — all", "checks green")

# Emit TP rows (full path from scan.json) for the baseline table, grouped by rule
out = ["| # | Rule | Sev | Vị trí (repo military-youth) | Message (nguyên bản scan) |",
       "|---|---|---|---|---|"]
for r in rows:
    if r[5].strip("*") == "TP":
        i = int(r[0])
        fd = f[i]
        loc = f"{fd['location']['file']}:{fd['location']['line']}"
        msg = fd["message"].replace("|", "/")
        out.append(f"| {i} | {r[1]} | {r[2]} | `{loc}` | {msg} |")
open("/tmp/w505-tp-rows.md", "w", encoding="utf-8").write("\n".join(out) + "\n")
print("tp-rows written:", len(out) - 2)
